<?php $page_title='Script Yönetimi - VideoKur'; $active_page='scripts'; ?>
<!DOCTYPE html><html lang="tr" x-data="{darkMode:localStorage.getItem('darkMode')==='1'}" :class="{'dark':darkMode}"><head>
<?php include __DIR__.'/components/_head.php'; ?>
<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.0/dist/cdn.min.js" defer></script>
</head><body class="bg-gray-100 dark:bg-slate-950 min-h-screen" x-data="scriptManager()" x-init="init()">
<div class="flex flex-col h-screen"><?php include __DIR__.'/components/_header.php'; ?><div class="flex flex-1 overflow-hidden"><?php include __DIR__.'/components/_sidebar.php'; ?>
<main class="flex-1 overflow-y-auto p-4 md:p-8"><div class="max-w-6xl mx-auto">
<div class="flex flex-col md:flex-row md:items-center justify-between gap-3 mb-6"><div><h1 class="text-2xl font-bold text-gray-900 dark:text-white">Script Yönetimi</h1><p class="text-sm text-gray-500 mt-1">Her script, videonun eksiksiz üretim profilidir.</p></div><button @click="openNew()" class="px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold">+ Yeni Script</button></div>
<div class="bg-white dark:bg-slate-800 border dark:border-slate-700 rounded-xl p-4 mb-5 flex flex-col md:flex-row gap-3"><input x-model="query" placeholder="Script ara..." class="flex-1 border dark:border-slate-600 dark:bg-slate-900 dark:text-white rounded-lg px-3 py-2"><select x-model="categoryFilter" class="border dark:border-slate-600 dark:bg-slate-900 dark:text-white rounded-lg px-3 py-2"><option value="all">Tüm kategoriler</option><template x-for="c in categories" :key="c.id"><option :value="c.id" x-text="c.name"></option></template></select></div>
<div class="grid sm:grid-cols-2 xl:grid-cols-3 gap-4"><template x-for="s in filtered" :key="s.id"><article class="bg-white dark:bg-slate-800 border dark:border-slate-700 rounded-xl p-5"><div class="flex justify-between gap-3"><div class="min-w-0"><h2 class="font-bold text-gray-900 dark:text-white truncate" x-text="s.name"></h2><p class="text-sm text-gray-500 line-clamp-2 mt-1" x-text="s.description||'Açıklama yok'"></p></div><span class="text-xs bg-blue-50 text-blue-700 h-fit px-2 py-1 rounded" x-text="videoLabel(s.videoType)"></span></div><div class="mt-4 space-y-1 text-xs text-gray-500"><p x-text="'Prompt: '+s.prompt.provider+' / '+s.prompt.model"></p><p x-text="'Görsel: '+(!s.visual.enabled?'Kapalı':s.visual.provider+' / '+(s.visual.model||'-'))"></p><p x-text="'Ses: '+(!s.voiceover.enabled?'Kapalı':s.voiceover.provider+' / '+(s.voiceover.voiceId||'-'))"></p><p x-text="'Müzik: '+musicLabel(s.music)"></p></div><div class="flex gap-2 mt-5"><button @click="edit(s)" class="flex-1 border dark:border-slate-600 rounded-lg py-2 text-sm dark:text-gray-200">Düzenle</button><button @click="removeScript(s.id)" class="px-3 border border-red-200 text-red-600 rounded-lg">Sil</button></div></article></template></div>
<p x-show="!filtered.length" class="text-center text-gray-500 py-16">Script bulunamadı.</p>
</div></main></div><?php include __DIR__.'/components/_footer.php'; ?></div>

<div x-show="modal" x-cloak class="fixed inset-0 z-50 bg-black/60 p-2 md:p-6 flex items-center justify-center" @click.self="close()"><div class="bg-white dark:bg-slate-900 rounded-xl shadow-2xl w-full max-w-4xl max-h-[96vh] flex flex-col">
<header class="p-4 border-b dark:border-slate-700 flex items-center justify-between"><div><h2 class="text-xl font-bold dark:text-white" x-text="editing?'Script Düzenle':'Yeni Script'"></h2><p class="text-xs text-gray-500">Üretimdeki tüm seçimler bu profilden alınır.</p></div><button @click="close()" class="text-2xl text-gray-400">×</button></header>
<form @submit.prevent="save()" class="overflow-y-auto p-4 space-y-3">
<template x-for="section in sections" :key="section.id"><section class="border dark:border-slate-700 rounded-xl overflow-hidden"><button type="button" @click="openSection=openSection===section.id?'':section.id" class="w-full p-4 flex items-center justify-between bg-gray-50 dark:bg-slate-800"><span class="font-semibold dark:text-white" x-text="section.icon+' '+section.label"></span><span x-text="openSection===section.id?'−':'+'"></span></button>
<div x-show="openSection===section.id" class="p-4 dark:text-gray-200">
<template x-if="section.id==='general'"><div class="grid md:grid-cols-2 gap-4"><label class="text-sm">Ad *<input x-model.trim="form.name" required class="field"></label><label class="text-sm">Kategori<select x-model="form.categoryId" class="field"><template x-for="c in categories" :key="c.id"><option :value="c.id" x-text="c.name"></option></template></select></label><label class="text-sm md:col-span-2">Açıklama<input x-model.trim="form.description" class="field"></label><label class="text-sm">Maksimum süre (sn)<input type="number" min="10" max="3600" x-model.number="form.maxDuration" class="field"></label><label class="text-sm">Video tipi<select x-model="form.videoType" class="field"><option value="short">Short (9:16)</option><option value="square">Kare (1:1)</option><option value="wide">Geniş (16:9)</option></select></label></div></template>
<template x-if="section.id==='visual'"><div class="space-y-4"><label class="flex gap-2"><input type="checkbox" x-model="form.visual.enabled"> Görsel üret</label><div x-show="form.visual.enabled" class="grid md:grid-cols-2 gap-4"><label class="text-sm">Servis<select x-model="form.visual.provider" @change="syncModel('visual')" class="field"><template x-for="p in providers('visual')" :key="p.id"><option :value="p.id" x-text="p.label"></option></template></select></label><label class="text-sm" x-show="cap('visual',form.visual.provider)?.supportsModel">Model<select x-model="form.visual.model" class="field"><template x-for="m in models('visual',form.visual.provider)" :key="m"><option :value="m" x-text="m"></option></template></select></label><label class="text-sm" x-show="form.visual.provider==='fal'">Adım sayısı<input type="number" min="1" max="50" x-model.number="form.visual.options.steps" class="field"></label></div></div></template>
<template x-if="section.id==='voice'">
  <div class="space-y-4">
    <label class="flex gap-2"><input type="checkbox" x-model="form.voiceover.enabled"> Seslendirme üret</label>
    <div x-show="form.voiceover.enabled" class="grid md:grid-cols-2 gap-4">
      <label class="text-sm">Servis
        <select x-model="form.voiceover.provider" @change="syncVoice()" class="field">
          <template x-for="p in providers('voiceover')" :key="p.id"><option :value="p.id" x-text="p.label"></option></template>
        </select>
      </label>
      <label class="text-sm" x-show="cap('voiceover',form.voiceover.provider)?.supportsModel">Model
        <select x-model="form.voiceover.model" class="field">
          <template x-for="m in models('voiceover',form.voiceover.provider)" :key="m"><option :value="m" x-text="m"></option></template>
        </select>
      </label>
      <label class="text-sm md:col-span-2">Ses ID
        <input list="primaryVoiceOptions" x-model.trim="form.voiceover.voiceId" placeholder="Ses seçin veya Voice ID girin" class="field">
        <datalist id="primaryVoiceOptions">
          <template x-for="v in voices()" :key="v.id"><option :value="v.id" x-text="v.name + (v.language ? ' · '+v.language : '')"></option></template>
        </datalist>
        <span x-show="cap('voiceover',form.voiceover.provider)?.voicesError" class="block mt-1 text-xs text-amber-600" x-text="cap('voiceover',form.voiceover.provider)?.voicesError"></span>
      </label>
      <label class="text-sm">Fallback
        <select x-model="form.voiceover.fallbackProvider" @change="syncFallback()" class="field">
          <option value="">Yok</option>
          <template x-for="p in providers('voiceover').filter(p=>p.id!==form.voiceover.provider)" :key="p.id"><option :value="p.id" x-text="p.label"></option></template>
        </select>
      </label>
      <label class="text-sm" x-show="fallbackCap()?.supportsModel">Fallback model
        <select x-model="form.voiceover.fallbackModel" class="field">
          <template x-for="m in fallbackModels()" :key="m"><option :value="m" x-text="m"></option></template>
        </select>
      </label>
      <label class="text-sm md:col-span-2" x-show="form.voiceover.fallbackProvider">Fallback ses ID
        <input list="fallbackVoiceOptions" x-model.trim="form.voiceover.fallbackVoiceId" placeholder="Ses seçin veya Voice ID girin" class="field">
        <datalist id="fallbackVoiceOptions">
          <template x-for="v in fallbackVoices()" :key="v.id"><option :value="v.id" x-text="v.name + (v.language ? ' · '+v.language : '')"></option></template>
        </datalist>
      </label>
    </div>
  </div>
</template><template x-if="section.id==='music'"><div class="space-y-4"><label class="text-sm">Müzik kullanımı<select x-model="form.music.mode" @change="musicModeChanged()" class="field"><option value="off">Müzik yok</option><option value="single">Tek müzik</option><option value="rotate">Sıralı rotasyon</option></select></label><div x-show="form.music.mode!=='off'"><p class="text-xs text-gray-500 mb-2">Parçalara tıklayarak seçin. Rotasyonda yukarı/aşağı düğmeleri kullanım sırasını belirler.</p><div class="space-y-2"><template x-for="t in activeTracks" :key="t.id"><div class="flex items-center gap-2 border dark:border-slate-700 rounded-lg p-2"><input type="checkbox" :checked="form.music.trackIds.includes(t.id)" @change="toggleTrack(t.id)"><span class="flex-1 text-sm" x-text="t.name"></span><button type="button" @click="moveTrack(t.id,-1)" class="px-2">↑</button><button type="button" @click="moveTrack(t.id,1)" class="px-2">↓</button></div></template></div><label class="text-sm block mt-3">Ses seviyesi: <span x-text="form.music.volumeDb+' dB'"></span><input type="range" min="-60" max="0" x-model.number="form.music.volumeDb" class="w-full"></label></div></div></template>
<template x-if="section.id==='subtitle'"><div class="space-y-4"><label class="flex gap-2"><input type="checkbox" x-model="form.subtitles.enabled"> Altyazı ekle</label><div x-show="form.subtitles.enabled" class="grid grid-cols-2 md:grid-cols-3 gap-4"><label class="text-sm">Yazı tipi<input x-model="form.subtitles.style.FontName" class="field"></label><label class="text-sm">Boyut<input type="number" min="8" max="100" x-model.number="form.subtitles.style.FontSize" class="field"></label><label class="text-sm">Satır kelime sayısı<input type="number" min="1" max="12" x-model.number="form.subtitles.maxWordsPerLine" class="field"></label><label class="text-sm">Yazı rengi<input type="color" x-model="form.subtitles.style.PrimaryColour" class="field h-11"></label><label class="text-sm">Kenarlık rengi<input type="color" x-model="form.subtitles.style.OutlineColour" class="field h-11"></label><label class="text-sm">Arka plan rengi<input type="color" x-model="form.subtitles.style.BackColour" class="field h-11"></label><label class="text-sm">Kenarlık tipi<select x-model.number="form.subtitles.style.BorderStyle" class="field"><option :value="1">Dış çizgi</option><option :value="3">Dış çizgi</option><option :value="4">Arka plan kutusu</option></select></label><label class="text-sm">Kenarlık<input type="number" min="0" max="10" x-model.number="form.subtitles.style.Outline" class="field"></label><label class="text-sm">Gölge<input type="number" min="0" max="10" x-model.number="form.subtitles.style.Shadow" class="field"></label><label class="text-sm">Dikey boşluk<input type="number" min="0" max="500" x-model.number="form.subtitles.style.MarginV" class="field"></label><label class="text-sm">Sol boşluk<input type="number" min="0" max="500" x-model.number="form.subtitles.style.MarginL" class="field"></label><label class="text-sm">Sağ boşluk<input type="number" min="0" max="500" x-model.number="form.subtitles.style.MarginR" class="field"></label><label class="text-sm">Hizalama<select x-model.number="form.subtitles.style.Alignment" class="field"><option :value="1">Sol alt</option><option :value="2">Orta alt</option><option :value="3">Sağ alt</option><option :value="5">Sol orta</option><option :value="6">Orta</option><option :value="7">Sol üst</option><option :value="8">Orta üst</option><option :value="9">Sağ üst</option></select></label><label class="flex items-end gap-2 pb-3"><input type="checkbox" x-model.number="form.subtitles.style.Bold" :true-value="1" :false-value="0"> Kalın</label></div></div></template>
<template x-if="section.id==='prompt'"><div class="space-y-4"><div class="grid md:grid-cols-2 gap-4"><label class="text-sm">Script servisi<select x-model="form.prompt.provider" @change="syncModel('prompt')" class="field"><template x-for="p in providers('prompt')" :key="p.id"><option :value="p.id" x-text="p.label"></option></template></select></label><label class="text-sm">Model<select x-model="form.prompt.model" class="field"><template x-for="m in models('prompt',form.prompt.provider)" :key="m"><option :value="m" x-text="m"></option></template></select></label></div><label class="text-sm">Prompt metni *<textarea x-model="form.prompt.text" rows="18" required class="field font-mono"></textarea></label><p class="text-xs text-gray-500">Değişkenler: {{TITLE}}, {{TEXT}}, {{MAX_DURATION}}</p></div></template>
</div></section></template>
<div x-show="error" class="p-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm" x-text="error"></div>
<footer class="sticky bottom-0 bg-white dark:bg-slate-900 border-t dark:border-slate-700 pt-4 flex justify-end gap-3"><button type="button" @click="close()" class="px-4 py-2 border rounded-lg">İptal</button><button :disabled="saving" class="px-5 py-2 bg-blue-600 text-white rounded-lg disabled:opacity-50" x-text="saving?'Kaydediliyor...':'Kaydet'"></button></footer>
</form></div></div>
<style>.field{display:block;width:100%;margin-top:.35rem;border:1px solid rgb(209 213 219);border-radius:.5rem;padding:.6rem .75rem;background:transparent}.dark .field{border-color:rgb(71 85 105);color:white;background:rgb(15 23 42)}[x-cloak]{display:none!important}</style>
<script>
function scriptManager(){return{sidebarOpen:false,scripts:[],categories:[],capabilities:{prompt:[],visual:[],voiceover:[]},tracks:[],query:'',categoryFilter:'all',modal:false,editing:false,saving:false,error:'',openSection:'general',sections:[{id:'general',label:'Genel',icon:'⚙️'},{id:'visual',label:'Görsel',icon:'🖼️'},{id:'voice',label:'Seslendirme',icon:'🎙️'},{id:'music',label:'Müzik',icon:'🎵'},{id:'subtitle',label:'Altyazı',icon:'💬'},{id:'prompt',label:'Prompt ve Script Modeli',icon:'📝'}],form:{prompt:{provider:'',model:'',text:''},visual:{enabled:true,provider:'',model:'',options:{steps:4}},voiceover:{enabled:true,provider:'',model:'',voiceId:'',fallbackProvider:'',fallbackModel:'',fallbackVoiceId:''},music:{mode:'off',trackIds:[],volumeDb:-22},subtitles:{enabled:true,maxWordsPerLine:5,style:{}}},
async init(){await Promise.all([this.loadScripts(),this.loadCaps(),this.loadMusic()]);},get filtered(){let q=this.query.toLocaleLowerCase('tr');return this.scripts.filter(s=>(this.categoryFilter==='all'||s.categoryId===this.categoryFilter)&&(!q||(s.name+' '+s.description+' '+s.contentType).toLocaleLowerCase('tr').includes(q)));},get activeTracks(){return this.tracks.filter(t=>t.active!==false);},providers(g){return(this.capabilities[g]||[]).filter(p=>p.available);},cap(g,id){return(this.capabilities[g]||[]).find(p=>p.id===id);},models(g,id){return this.cap(g,id)?.models||[];},voices(){return this.cap('voiceover',this.form.voiceover?.provider)?.voices||[];},fallbackCap(){return this.cap('voiceover',this.form.voiceover?.fallbackProvider);},fallbackModels(){return this.fallbackCap()?.models||[];},fallbackVoices(){return this.fallbackCap()?.voices||[];},videoLabel(v){return v==='wide'?'Geniş':v==='square'?'Kare':'Short';},musicLabel(m){return m.mode==='rotate'?`${m.trackIds.length} parça rotasyon`:m.mode==='single'?'Tek parça':'Yok';},
async loadScripts(){let d=await(await fetch('/api/scripts.php')).json();this.scripts=d.scripts||[];this.categories=d.categories||[];},async loadCaps(){let d=await(await fetch('/api/provider_capabilities.php?include=voice_catalogs')).json();this.capabilities=d.capabilities||this.capabilities;},async loadMusic(){let d=await(await fetch('/api/music.php')).json();this.tracks=d.tracks||[];},
blank(){let pp=this.providers('prompt')[0],vp=this.providers('visual')[0],ap=this.providers('voiceover')[0];return{schemaVersion:2,id:'',name:'',description:'',categoryId:this.categories[0]?.id||'genel',contentType:'',videoType:'short',maxDuration:55,prompt:{provider:pp?.id||'',model:pp?.models?.[0]||'',text:'Sen bir profesyonel kısa video scripti yazarısın.\n\nBaşlık: {{TITLE}}\nMetin: {{TEXT}}\nMaksimum süre: {{MAX_DURATION}} saniye.\n\nSadece geçerli JSON döndür.'},visual:{enabled:true,provider:vp?.id||'',model:vp?.models?.[0]||'',options:{steps:4}},voiceover:{enabled:true,provider:ap?.id||'',model:ap?.models?.[0]||'',voiceId:ap?.voices?.[0]?.id||'',fallbackProvider:'',fallbackModel:'',fallbackVoiceId:''},music:{mode:'off',trackIds:[],volumeDb:-22},subtitles:{enabled:true,maxWordsPerLine:5,style:{FontName:'Arial',FontSize:24,PrimaryColour:'#FFFFFF',OutlineColour:'#000000',BackColour:'#000000',BorderStyle:3,Outline:2,Shadow:1,MarginV:80,MarginL:40,MarginR:40,Alignment:2,Bold:1}}};},openNew(){this.editing=false;this.form=this.blank();this.error='';this.openSection='general';this.modal=true;},edit(s){this.editing=true;this.form=JSON.parse(JSON.stringify(s));this.error='';this.openSection='general';this.modal=true;},close(){this.modal=false;},syncModel(g){let obj=g==='prompt'?this.form.prompt:this.form.visual,p=this.cap(g,obj.provider);obj.model=p?.models?.[0]||'';},syncVoice(){let p=this.cap('voiceover',this.form.voiceover.provider);this.form.voiceover.model=p?.models?.[0]||'';this.form.voiceover.voiceId=p?.voices?.[0]?.id||'';if(this.form.voiceover.fallbackProvider===this.form.voiceover.provider){this.form.voiceover.fallbackProvider='';this.syncFallback();}},syncFallback(){let p=this.fallbackCap();this.form.voiceover.fallbackModel=p?.models?.[0]||'';this.form.voiceover.fallbackVoiceId=p?.voices?.[0]?.id||'';},musicModeChanged(){if(this.form.music.mode==='off')this.form.music.trackIds=[];if(this.form.music.mode==='single'&&this.form.music.trackIds.length>1)this.form.music.trackIds=this.form.music.trackIds.slice(0,1);},toggleTrack(id){let a=this.form.music.trackIds,i=a.indexOf(id);if(i>=0)a.splice(i,1);else{if(this.form.music.mode==='single')a.splice(0,a.length);a.push(id);}},moveTrack(id,d){let a=this.form.music.trackIds,i=a.indexOf(id),n=i+d;if(i<0||n<0||n>=a.length)return;[a[i],a[n]]=[a[n],a[i]];},
async save(){this.saving=true;this.error='';try{let cat=this.categories.find(c=>c.id===this.form.categoryId);this.form.contentType=cat?.name||this.form.categoryId;let r=await fetch('/api/scripts.php',{method:this.editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.form)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Script kaydedilemedi.');await this.loadScripts();this.close();}catch(e){this.error=e.message;let msg=e.message.toLocaleLowerCase('tr');this.openSection=msg.includes('müzik')?'music':msg.includes('ses')||msg.includes('voice')?'voice':msg.includes('görsel')?'visual':msg.includes('prompt')||msg.includes('model')?'prompt':'general';}finally{this.saving=false;}},async removeScript(id){if(!confirm('Script silinsin mi?'))return;let r=await fetch('/api/scripts.php',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)await this.loadScripts();else alert((await r.json()).error||'Silinemedi.');}}
}
</script></body></html>
