<?php
require_once dirname(__DIR__) . '/includes/auth.php';
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') exit;
require_once __DIR__ . '/script_profile_helpers.php';
$baseDir = dirname(__DIR__);
function scripts_respond($payload, $status = 200) { http_response_code($status); echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); exit; }
function scripts_input() { $input=json_decode((string)file_get_contents('php://input'),true); if(!is_array($input)) scripts_respond(['success'=>false,'error'=>'Geçersiz JSON verisi.'],400); return $input; }
function scripts_profile_from_input($input,$baseDir,$existing=[]) { $merged=array_replace_recursive($existing,$input); $categoryId=vp_normalize_category_id($merged['categoryId']??$merged['contentType']??'genel'); $data=vp_load_script_data($baseDir,true); $profile=vp_normalize_profile($merged,$baseDir,vp_category_name($data['categories'],$categoryId)); $profile['id']=trim((string)($existing['id']??$input['id']??'')); $profile['createdAt']=$existing['createdAt']??$input['createdAt']??date('c'); $profile['updatedAt']=date('c'); return $profile; }
$method=$_SERVER['REQUEST_METHOD']; $data=vp_load_script_data($baseDir,true);
if($method==='GET'){ if(isset($_GET['id'])){ $script=vp_find_script($baseDir,trim((string)$_GET['id'])); if(!$script) scripts_respond(['success'=>false,'error'=>'Script bulunamadı.'],404); scripts_respond($script); } scripts_respond($data); }
if($method==='POST'){ $input=scripts_input(); if(($input['action']??'create_script')==='create_category'){ $name=trim((string)($input['name']??'')); if($name==='') scripts_respond(['success'=>false,'error'=>'Kategori adı gerekli.'],400); $id=vp_normalize_category_id($input['id']??$name); foreach($data['categories'] as $category) if(($category['id']??'')===$id) scripts_respond(['success'=>false,'error'=>'Kategori zaten var.'],409); $data['categories'][]=['id'=>$id,'name'=>$name,'active'=>true,'createdAt'=>date('c'),'updatedAt'=>date('c')]; if(!vp_save_script_data($baseDir,$data)) scripts_respond(['success'=>false,'error'=>'Kategori kaydedilemedi.'],500); scripts_respond(['success'=>true,'categories'=>$data['categories']]); } $input['id']='script_'.str_replace('.','_',uniqid('',true)); $profile=scripts_profile_from_input($input,$baseDir); $errors=vp_validate_profile($profile,$baseDir); if($errors) scripts_respond(['success'=>false,'error'=>$errors[0],'errors'=>$errors],422); $data['scripts'][]=$profile; if(!vp_save_script_data($baseDir,$data)) scripts_respond(['success'=>false,'error'=>'Script kaydedilemedi.'],500); scripts_respond(['success'=>true,'script'=>$profile],201); }
if($method==='PUT'){ $input=scripts_input(); if(($input['action']??'update_script')==='update_category'){ $id=vp_normalize_category_id($input['id']??''); $name=trim((string)($input['name']??'')); $found=false; if($name==='') scripts_respond(['success'=>false,'error'=>'Kategori adı gerekli.'],400); foreach($data['categories'] as &$category) if(($category['id']??'')===$id){$category['name']=$name;$category['updatedAt']=date('c');$found=true;break;} unset($category); if(!$found) scripts_respond(['success'=>false,'error'=>'Kategori bulunamadı.'],404); foreach($data['scripts'] as &$script) if(($script['categoryId']??'')===$id){$script['contentType']=$name;$script['updatedAt']=date('c');} unset($script); if(!vp_save_script_data($baseDir,$data)) scripts_respond(['success'=>false,'error'=>'Kategori kaydedilemedi.'],500); scripts_respond(['success'=>true]); } $id=trim((string)($input['id']??'')); $index=null; foreach($data['scripts'] as $i=>$script) if(($script['id']??'')===$id){$index=$i;break;} if($index===null) scripts_respond(['success'=>false,'error'=>'Script bulunamadı.'],404); $profile=scripts_profile_from_input($input,$baseDir,$data['scripts'][$index]); $errors=vp_validate_profile($profile,$baseDir); if($errors) scripts_respond(['success'=>false,'error'=>$errors[0],'errors'=>$errors],422); $data['scripts'][$index]=$profile; if(!vp_save_script_data($baseDir,$data)) scripts_respond(['success'=>false,'error'=>'Script kaydedilemedi.'],500); scripts_respond(['success'=>true,'script'=>$profile]); }
if($method==='DELETE'){ $input=scripts_input(); if(($input['action']??'delete_script')==='delete_category'){ $id=vp_normalize_category_id($input['id']??''); foreach($data['scripts'] as $script) if(($script['categoryId']??'')===$id) scripts_respond(['success'=>false,'error'=>'Bu kategori scriptlerde kullanılıyor.'],409); $before=count($data['categories']);$data['categories']=array_values(array_filter($data['categories'],fn($c)=>($c['id']??'')!==$id));if($before===count($data['categories']))scripts_respond(['success'=>false,'error'=>'Kategori bulunamadı.'],404);if(!vp_save_script_data($baseDir,$data))scripts_respond(['success'=>false,'error'=>'Kategori silinemedi.'],500);scripts_respond(['success'=>true,'categories'=>$data['categories']]);} $id=trim((string)($input['id']??''));$before=count($data['scripts']);$data['scripts']=array_values(array_filter($data['scripts'],fn($s)=>($s['id']??'')!==$id));if($before===count($data['scripts']))scripts_respond(['success'=>false,'error'=>'Script bulunamadı.'],404);if(!vp_save_script_data($baseDir,$data))scripts_respond(['success'=>false,'error'=>'Script silinemedi.'],500);scripts_respond(['success'=>true]); }
scripts_respond(['success'=>false,'error'=>'Desteklenmeyen yöntem.'],405);
